// Terrain types from the game
export const TERRAIN_TYPES = [
  { id: 1, name: "Ocean" },
  { id: 2, name: "Coastal" },
  { id: 3, name: "Islands" },
  { id: 4, name: "Desert" },
  { id: 5, name: "Paved Roads" },
  { id: 6, name: "Plains" },
  { id: 7, name: "Unpaved Roads" },
  { id: 8, name: "Grasslands" },
  { id: 9, name: "Rocky Desert" },
  { id: 10, name: "Hills" },
  { id: 11, name: "Swamp" },
  { id: 12, name: "Snow" },
  { id: 13, name: "Rain Forest/Jungle" },
  { id: 14, name: "Mountains" },
  { id: 15, name: "Light Forest" },
  { id: 16, name: "Heavy Forest" },
  { id: 17, name: "Jungle Mountains" },
  { id: 18, name: "Forested Mountains" },
  { id: 19, name: "High Altitude" },
  { id: 20, name: "Lake" },
  { id: 21, name: "River" },
  { id: 22, name: "Ice" },
  { id: 23, name: "Farmland" },
  { id: 24, name: "Wasteland" },
  { id: 25, name: "Exclusion Zone" },
] as const

export type TerrainType = (typeof TERRAIN_TYPES)[number]

// Government structure types
export type GovernmentStructureType =
  | "Constitutional Monarchy"
  | "Parliamentary Republic"
  | "Democracy"
  | "Federal Republic"
  | "Republic"
  | "Limited democracy"
  | "Parliamentary democracy"
  | "Multiparty Democracy"
  | "Constitutional Democracy"
  | "Democratic Republic"
  | "Communist state"
  | "Theocratic Republic"
  | "Monarchy"
  | "Emirate"
  | "Dictatorship"
  | "transitional government"
  | "Military junta"

export type GovernmentPerception = "Full Democracy" | "Flawed Democracy" | "Hybrid Regime" | "Authoritarian Regime"

export type CapitalPunishmentType = "Inactive" | "Active" | "Rare"

export type RegulationType = "Banned" | "Regulated" | "Legal"

export interface Country {
  code: number
  name: string
  president: string
  population: number
  populationRating: number
  motto: string
  nationality: string
  governmentStructure: GovernmentStructureType
  governmentPerception: GovernmentPerception
  governmentCorruption: number
  presidentialTerm: number
  leaderTitle: string
  militaryServices: number
  militaryBudget: number
  intelligenceServices: number
  intelligenceBudget: number
  capitalPunishment: CapitalPunishmentType
  mediaFreedom: number
  lawEnforcement: number
  lawEnforcementBudget: number
  gdpNational: number
  gdpPerCapita: number
  healthcare: number
  higherEducation: number
  socialDevelopment: number
  lifestyle: number
  terrorismActivity: number
  cyberCapabilities: number
  digitalDevelopment: number
  science: number
  cloning: RegulationType
  lswActivity: number
  lswRegulations: RegulationType
  vigilantism: RegulationType
  presidentGender: "Male" | "Female" | ""
  // Computed/display fields
  flag?: string
  partners?: string[]
  adversaries?: string[]
}

export type CityType =
  | "Military"
  | "Political"
  | "Educational"
  | "Company"
  | "Industrial"
  | "Temple"
  | "Mining"
  | "Resort"
  | "Seaport"

export type PopulationType = "Mega City" | "Large City" | "City" | "Small City" | "Town" | "Small Town"

export interface City {
  sector: string
  countryCode: number
  cultureCode: number
  name: string
  country: string
  population: number
  populationRating: number
  populationType: PopulationType
  cityTypes: CityType[]
  hvt: string
  crimeIndex: number
  safetyIndex: number
}

// All countries data from CSV
export const COUNTRIES: Country[] = [
  {
    code: 163,
    name: "Slovenia",
    president: "Edvard Cencič",
    population: 2078938,
    populationRating: 30,
    motto: "None",
    nationality: "Slovenian",
    governmentStructure: "Parliamentary Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 59,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 33,
    militaryBudget: 40,
    intelligenceServices: 20,
    intelligenceBudget: 33,
    capitalPunishment: "Inactive",
    mediaFreedom: 76,
    lawEnforcement: 63,
    lawEnforcementBudget: 64,
    gdpNational: 46,
    gdpPerCapita: 64,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 77,
    terrorismActivity: 0,
    cyberCapabilities: 59,
    digitalDevelopment: 70,
    science: 20,
    cloning: "Banned",
    lswActivity: 31,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "Male",
  },
  {
    code: 162,
    name: "Norway",
    president: "Anne Dahl Bøyum",
    population: 5421241,
    populationRating: 38,
    motto: "Everything for Norway",
    nationality: "Norwegian",
    governmentStructure: "Democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 85,
    presidentialTerm: 0,
    leaderTitle: "Monarch",
    militaryServices: 53,
    militaryBudget: 55,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 90,
    lawEnforcement: 76,
    lawEnforcementBudget: 82,
    gdpNational: 56,
    gdpPerCapita: 88,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 62,
    digitalDevelopment: 85,
    science: 20,
    cloning: "Banned",
    lswActivity: 27,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "Female",
  },
  {
    code: 159,
    name: "Austria",
    president: "Catherine Maurer",
    population: 9006458,
    populationRating: 44,
    motto: "None",
    nationality: "Austrian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 75,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 44,
    militaryBudget: 52,
    intelligenceServices: 20,
    intelligenceBudget: 40,
    capitalPunishment: "Inactive",
    mediaFreedom: 83,
    lawEnforcement: 42,
    lawEnforcementBudget: 63,
    gdpNational: 59,
    gdpPerCapita: 84,
    healthcare: 85,
    higherEducation: 86,
    socialDevelopment: 90,
    lifestyle: 89,
    terrorismActivity: 32,
    cyberCapabilities: 68,
    digitalDevelopment: 77,
    science: 66,
    cloning: "Banned",
    lswActivity: 24,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "Female",
  },
  {
    code: 128,
    name: "New Zealand",
    president: "Rebecca Hearn",
    population: 4822233,
    populationRating: 36,
    motto: "Onward",
    nationality: "Kiwi",
    governmentStructure: "Democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 90,
    presidentialTerm: 5,
    leaderTitle: "Governor-General",
    militaryServices: 35,
    militaryBudget: 45,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 89,
    lawEnforcement: 11,
    lawEnforcementBudget: 46,
    gdpNational: 55,
    gdpPerCapita: 80,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 86,
    terrorismActivity: 43,
    cyberCapabilities: 51,
    digitalDevelopment: 77,
    science: 59,
    cloning: "Banned",
    lswActivity: 34,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "Female",
  },
  {
    code: 120,
    name: "Iceland",
    president: "Agla Árnadóttir",
    population: 341243,
    populationRating: 20,
    motto: "None",
    nationality: "Icelander",
    governmentStructure: "Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 77,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 20,
    militaryBudget: 32,
    intelligenceServices: 20,
    intelligenceBudget: 32,
    capitalPunishment: "Inactive",
    mediaFreedom: 84,
    lawEnforcement: 38,
    lawEnforcementBudget: 63,
    gdpNational: 43,
    gdpPerCapita: 88,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 85,
    terrorismActivity: 0,
    cyberCapabilities: 55,
    digitalDevelopment: 78,
    science: 36,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "Female",
  },
  {
    code: 113,
    name: "Finland",
    president: "Leena Tolvanen",
    population: 5540720,
    populationRating: 39,
    motto: "Home, Religion and the Fatherland",
    nationality: "Finnish",
    governmentStructure: "Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 87,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 43,
    militaryBudget: 49,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 90,
    lawEnforcement: 48,
    lawEnforcementBudget: 66,
    gdpNational: 55,
    gdpPerCapita: 84,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 84,
    digitalDevelopment: 80,
    science: 65,
    cloning: "Banned",
    lswActivity: 31,
    lswRegulations: "Legal",
    vigilantism: "Regulated",
    presidentGender: "Female",
  },
  {
    code: 107,
    name: "Denmark",
    president: "",
    population: 5792202,
    populationRating: 39,
    motto: "God's help, the love of the people, Denmark's strength",
    nationality: "Danish",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 90,
    presidentialTerm: 4,
    leaderTitle: "Monarch",
    militaryServices: 44,
    militaryBudget: 50,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 90,
    lawEnforcement: 76,
    lawEnforcementBudget: 82,
    gdpNational: 56,
    gdpPerCapita: 87,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 83,
    digitalDevelopment: 90,
    science: 65,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 106,
    name: "Czech Republic",
    president: "",
    population: 10708981,
    populationRating: 46,
    motto: "Truth prevails",
    nationality: "Czech",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 55,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 50,
    militaryBudget: 53,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 76,
    lawEnforcement: 26,
    lawEnforcementBudget: 44,
    gdpNational: 55,
    gdpPerCapita: 62,
    healthcare: 90,
    higherEducation: 89,
    socialDevelopment: 90,
    lifestyle: 83,
    terrorismActivity: 20,
    cyberCapabilities: 90,
    digitalDevelopment: 69,
    science: 65,
    cloning: "Banned",
    lswActivity: 26,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 92,
    name: "Hong Kong",
    president: "",
    population: 7496981,
    populationRating: 42,
    motto: "None",
    nationality: "None",
    governmentStructure: "Limited democracy",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 78,
    presidentialTerm: 5,
    leaderTitle: "Chief Executive",
    militaryServices: 25,
    militaryBudget: 41,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 69,
    lawEnforcement: 45,
    lawEnforcementBudget: 65,
    gdpNational: 56,
    gdpPerCapita: 84,
    healthcare: 85,
    higherEducation: 88,
    socialDevelopment: 90,
    lifestyle: 85,
    terrorismActivity: 0,
    cyberCapabilities: 69,
    digitalDevelopment: 79,
    science: 64,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Banned",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 89,
    name: "Netherlands",
    president: "Henk Klaassens",
    population: 17134872,
    populationRating: 48,
    motto: "I will maintain",
    nationality: "Dutchman",
    governmentStructure: "Democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 83,
    presidentialTerm: 4,
    leaderTitle: "Monarch",
    militaryServices: 51,
    militaryBudget: 59,
    intelligenceServices: 20,
    intelligenceBudget: 44,
    capitalPunishment: "Inactive",
    mediaFreedom: 90,
    lawEnforcement: 19,
    lawEnforcementBudget: 52,
    gdpNational: 67,
    gdpPerCapita: 85,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 83,
    digitalDevelopment: 88,
    science: 70,
    cloning: "Banned",
    lswActivity: 31,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 68,
    name: "United Kingdom",
    president: "Jessica Hyde",
    population: 67886011,
    populationRating: 57,
    motto: "God and my right",
    nationality: "British",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 78,
    presidentialTerm: 5,
    leaderTitle: "Monarch",
    militaryServices: 75,
    militaryBudget: 78,
    intelligenceServices: 60,
    intelligenceBudget: 70,
    capitalPunishment: "Inactive",
    mediaFreedom: 78,
    lawEnforcement: 56,
    lawEnforcementBudget: 68,
    gdpNational: 80,
    gdpPerCapita: 79,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 47,
    cyberCapabilities: 79,
    digitalDevelopment: 84,
    science: 79,
    cloning: "Banned",
    lswActivity: 65,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "Female",
  },
  {
    code: 61,
    name: "Taiwan",
    president: "",
    population: 23816775,
    populationRating: 51,
    motto: "None",
    nationality: "Taiwanese",
    governmentStructure: "Multiparty Democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 66,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 63,
    militaryBudget: 63,
    intelligenceServices: 40,
    intelligenceBudget: 52,
    capitalPunishment: "Active",
    mediaFreedom: 76,
    lawEnforcement: 42,
    lawEnforcementBudget: 53,
    gdpNational: 63,
    gdpPerCapita: 64,
    healthcare: 90,
    higherEducation: 88,
    socialDevelopment: 90,
    lifestyle: 88,
    terrorismActivity: 20,
    cyberCapabilities: 69,
    digitalDevelopment: 79,
    science: 24,
    cloning: "Banned",
    lswActivity: 39,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 59,
    name: "Switzerland",
    president: "",
    population: 8654622,
    populationRating: 43,
    motto: "One for all, all for one",
    nationality: "Swede",
    governmentStructure: "Federal Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 89,
    presidentialTerm: 4,
    leaderTitle: "President of the Confederation",
    militaryServices: 53,
    militaryBudget: 59,
    intelligenceServices: 30,
    intelligenceBudget: 48,
    capitalPunishment: "Inactive",
    mediaFreedom: 89,
    lawEnforcement: 18,
    lawEnforcementBudget: 54,
    gdpNational: 65,
    gdpPerCapita: 90,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 25,
    cyberCapabilities: 76,
    digitalDevelopment: 89,
    science: 73,
    cloning: "Banned",
    lswActivity: 28,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 58,
    name: "Sweden",
    president: "",
    population: 10099265,
    populationRating: 45,
    motto: "For Sweden – in the time",
    nationality: "Swazi",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 86,
    presidentialTerm: 4,
    leaderTitle: "Monarch",
    militaryServices: 54,
    militaryBudget: 58,
    intelligenceServices: 20,
    intelligenceBudget: 41,
    capitalPunishment: "Inactive",
    mediaFreedom: 90,
    lawEnforcement: 45,
    lawEnforcementBudget: 65,
    gdpNational: 62,
    gdpPerCapita: 85,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 83,
    digitalDevelopment: 87,
    science: 68,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 55,
    name: "Spain",
    president: "",
    population: 46754778,
    populationRating: 56,
    motto: "Further beyond",
    nationality: "Spaniard",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 64,
    presidentialTerm: 0,
    leaderTitle: "Monarch",
    militaryServices: 64,
    militaryBudget: 67,
    intelligenceServices: 40,
    intelligenceBudget: 55,
    capitalPunishment: "Inactive",
    mediaFreedom: 79,
    lawEnforcement: 12,
    lawEnforcementBudget: 39,
    gdpNational: 70,
    gdpPerCapita: 65,
    healthcare: 85,
    higherEducation: 83,
    socialDevelopment: 90,
    lifestyle: 88,
    terrorismActivity: 28,
    cyberCapabilities: 87,
    digitalDevelopment: 73,
    science: 79,
    cloning: "Banned",
    lswActivity: 57,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 54,
    name: "South Korea",
    president: "",
    population: 51269185,
    populationRating: 56,
    motto: "To broadly benefit the human world",
    nationality: "South Korean",
    governmentStructure: "Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 62,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 77,
    militaryBudget: 74,
    intelligenceServices: 80,
    intelligenceBudget: 76,
    capitalPunishment: "Inactive",
    mediaFreedom: 76,
    lawEnforcement: 16,
    lawEnforcementBudget: 41,
    gdpNational: 71,
    gdpPerCapita: 66,
    healthcare: 85,
    higherEducation: 86,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 0,
    cyberCapabilities: 68,
    digitalDevelopment: 72,
    science: 72,
    cloning: "Banned",
    lswActivity: 58,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 51,
    name: "Singapore",
    president: "",
    population: 5850342,
    populationRating: 39,
    motto: "Onward Singapore",
    nationality: "Singaporean",
    governmentStructure: "Parliamentary Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 86,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 50,
    militaryBudget: 53,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Active",
    mediaFreedom: 44,
    lawEnforcement: 37,
    lawEnforcementBudget: 62,
    gdpNational: 56,
    gdpPerCapita: 87,
    healthcare: 90,
    higherEducation: 84,
    socialDevelopment: 90,
    lifestyle: 88,
    terrorismActivity: 0,
    cyberCapabilities: 63,
    digitalDevelopment: 81,
    science: 63,
    cloning: "Regulated",
    lswActivity: 29,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 35,
    name: "Japan",
    president: "",
    population: 126476461,
    populationRating: 70,
    motto: "None",
    nationality: "Japanese",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 76,
    presidentialTerm: 4,
    leaderTitle: "Emperor",
    militaryServices: 78,
    militaryBudget: 82,
    intelligenceServices: 80,
    intelligenceBudget: 83,
    capitalPunishment: "Active",
    mediaFreedom: 71,
    lawEnforcement: 82,
    lawEnforcementBudget: 79,
    gdpNational: 86,
    gdpPerCapita: 76,
    healthcare: 85,
    higherEducation: 85,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 63,
    digitalDevelopment: 79,
    science: 78,
    cloning: "Banned",
    lswActivity: 42,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 30,
    name: "Israel",
    president: "",
    population: 8655535,
    populationRating: 43,
    motto: "If you will it, it is no dream",
    nationality: "Israeli",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 61,
    presidentialTerm: 7,
    leaderTitle: "President",
    militaryServices: 65,
    militaryBudget: 61,
    intelligenceServices: 50,
    intelligenceBudget: 54,
    capitalPunishment: "Inactive",
    mediaFreedom: 69,
    lawEnforcement: 47,
    lawEnforcementBudget: 63,
    gdpNational: 57,
    gdpPerCapita: 79,
    healthcare: 90,
    higherEducation: 88,
    socialDevelopment: 90,
    lifestyle: 84,
    terrorismActivity: 47,
    cyberCapabilities: 67,
    digitalDevelopment: 75,
    science: 66,
    cloning: "Banned",
    lswActivity: 24,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 29,
    name: "Ireland",
    president: "",
    population: 4937786,
    populationRating: 37,
    motto: "Ireland forever",
    nationality: "Irish",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 73,
    presidentialTerm: 7,
    leaderTitle: "President",
    militaryServices: 31,
    militaryBudget: 44,
    intelligenceServices: 20,
    intelligenceBudget: 39,
    capitalPunishment: "Inactive",
    mediaFreedom: 88,
    lawEnforcement: 75,
    lawEnforcementBudget: 82,
    gdpNational: 57,
    gdpPerCapita: 88,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 88,
    terrorismActivity: 20,
    cyberCapabilities: 63,
    digitalDevelopment: 76,
    science: 58,
    cloning: "Banned",
    lswActivity: 32,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 23,
    name: "Germany",
    president: "Jurgen Worns",
    population: 83783942,
    populationRating: 57,
    motto: "Unity and justice and freedom",
    nationality: "German",
    governmentStructure: "Federal Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 81,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 67,
    militaryBudget: 76,
    intelligenceServices: 60,
    intelligenceBudget: 73,
    capitalPunishment: "Inactive",
    mediaFreedom: 84,
    lawEnforcement: 43,
    lawEnforcementBudget: 61,
    gdpNational: 85,
    gdpPerCapita: 79,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 47,
    cyberCapabilities: 90,
    digitalDevelopment: 82,
    science: 75,
    cloning: "Banned",
    lswActivity: 67,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 22,
    name: "France",
    president: "",
    population: 65273511,
    populationRating: 57,
    motto: "Liberty, equality, fraternity",
    nationality: "French",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 68,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 76,
    militaryBudget: 78,
    intelligenceServices: 60,
    intelligenceBudget: 70,
    capitalPunishment: "Inactive",
    mediaFreedom: 77,
    lawEnforcement: 45,
    lawEnforcementBudget: 62,
    gdpNational: 80,
    gdpPerCapita: 79,
    healthcare: 80,
    higherEducation: 81,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 45,
    cyberCapabilities: 82,
    digitalDevelopment: 78,
    science: 77,
    cloning: "Banned",
    lswActivity: 33,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 16,
    name: "Canada",
    president: "John Stone",
    population: 37742154,
    populationRating: 52,
    motto: "From sea to sea",
    nationality: "Canadian",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 76,
    presidentialTerm: 5,
    leaderTitle: "Governor General",
    militaryServices: 54,
    militaryBudget: 63,
    intelligenceServices: 40,
    intelligenceBudget: 56,
    capitalPunishment: "Inactive",
    mediaFreedom: 84,
    lawEnforcement: 72,
    lawEnforcementBudget: 77,
    gdpNational: 71,
    gdpPerCapita: 82,
    healthcare: 90,
    higherEducation: 89,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 38,
    cyberCapabilities: 66,
    digitalDevelopment: 77,
    science: 74,
    cloning: "Banned",
    lswActivity: 51,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 12,
    name: "Belgium",
    president: "",
    population: 11589623,
    populationRating: 47,
    motto: "Unity makes strength",
    nationality: "Belgian",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 76,
    presidentialTerm: 5,
    leaderTitle: "Monarch",
    militaryServices: 42,
    militaryBudget: 52,
    intelligenceServices: 20,
    intelligenceBudget: 41,
    capitalPunishment: "Inactive",
    mediaFreedom: 88,
    lawEnforcement: 42,
    lawEnforcementBudget: 62,
    gdpNational: 61,
    gdpPerCapita: 81,
    healthcare: 90,
    higherEducation: 89,
    socialDevelopment: 90,
    lifestyle: 90,
    terrorismActivity: 20,
    cyberCapabilities: 90,
    digitalDevelopment: 75,
    science: 69,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 6,
    name: "Australia",
    president: "",
    population: 25499884,
    populationRating: 51,
    motto: "Advance Australia",
    nationality: "Aussie",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Full Democracy",
    governmentCorruption: 78,
    presidentialTerm: 5,
    leaderTitle: "Governor-General",
    militaryServices: 66,
    militaryBudget: 69,
    intelligenceServices: 40,
    intelligenceBudget: 56,
    capitalPunishment: "Inactive",
    mediaFreedom: 80,
    lawEnforcement: 34,
    lawEnforcementBudget: 60,
    gdpNational: 71,
    gdpPerCapita: 85,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 90,
    lifestyle: 88,
    terrorismActivity: 24,
    cyberCapabilities: 66,
    digitalDevelopment: 78,
    science: 72,
    cloning: "Banned",
    lswActivity: 41,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 69,
    name: "United States",
    president: "",
    population: 331002651,
    populationRating: 82,
    motto: "In God We Trust",
    nationality: "American",
    governmentStructure: "Federal Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 69,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 90,
    militaryBudget: 90,
    intelligenceServices: 90,
    intelligenceBudget: 90,
    capitalPunishment: "Active",
    mediaFreedom: 76,
    lawEnforcement: 48,
    lawEnforcementBudget: 68,
    gdpNational: 90,
    gdpPerCapita: 87,
    healthcare: 90,
    higherEducation: 90,
    socialDevelopment: 78,
    lifestyle: 89,
    terrorismActivity: 49,
    cyberCapabilities: 79,
    digitalDevelopment: 83,
    science: 90,
    cloning: "Banned",
    lswActivity: 85,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 45,
    name: "Russia",
    president: "Aleksei Rostov",
    population: 145934462,
    populationRating: 70,
    motto: "None",
    nationality: "Russian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 28,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 86,
    militaryBudget: 81,
    intelligenceServices: 90,
    intelligenceBudget: 83,
    capitalPunishment: "Rare",
    mediaFreedom: 47,
    lawEnforcement: 49,
    lawEnforcementBudget: 50,
    gdpNational: 76,
    gdpPerCapita: 51,
    healthcare: 75,
    higherEducation: 82,
    socialDevelopment: 82,
    lifestyle: 82,
    terrorismActivity: 42,
    cyberCapabilities: 71,
    digitalDevelopment: 64,
    science: 78,
    cloning: "Regulated",
    lswActivity: 77,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 33,
    name: "China",
    president: "Qiang Zhang",
    population: 1439323776,
    populationRating: 90,
    motto: "Serve The People!",
    nationality: "Chinese",
    governmentStructure: "Communist state",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 77,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 84,
    militaryBudget: 86,
    intelligenceServices: 90,
    intelligenceBudget: 89,
    capitalPunishment: "Active",
    mediaFreedom: 21,
    lawEnforcement: 67,
    lawEnforcementBudget: 59,
    gdpNational: 87,
    gdpPerCapita: 51,
    healthcare: 75,
    higherEducation: 65,
    socialDevelopment: 76,
    lifestyle: 83,
    terrorismActivity: 20,
    cyberCapabilities: 82,
    digitalDevelopment: 69,
    science: 81,
    cloning: "Regulated",
    lswActivity: 90,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 25,
    name: "India",
    president: "Hamid Vinkat",
    population: 1380004385,
    populationRating: 89,
    motto: "Truth alone triumphs",
    nationality: "Indian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 42,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 80,
    militaryBudget: 80,
    intelligenceServices: 80,
    intelligenceBudget: 80,
    capitalPunishment: "Active",
    mediaFreedom: 53,
    lawEnforcement: 27,
    lawEnforcementBudget: 31,
    gdpNational: 80,
    gdpPerCapita: 35,
    healthcare: 65,
    higherEducation: 55,
    socialDevelopment: 65,
    lifestyle: 83,
    terrorismActivity: 74,
    cyberCapabilities: 59,
    digitalDevelopment: 40,
    science: 74,
    cloning: "Regulated",
    lswActivity: 90,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 15,
    name: "Brazil",
    president: "Mattheus De Souza",
    population: 212559417,
    populationRating: 75,
    motto: "Order and progress",
    nationality: "Brazilian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 36,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 73,
    militaryBudget: 75,
    intelligenceServices: 20,
    intelligenceBudget: 49,
    capitalPunishment: "Rare",
    mediaFreedom: 63,
    lawEnforcement: 68,
    lawEnforcementBudget: 58,
    gdpNational: 77,
    gdpPerCapita: 48,
    healthcare: 75,
    higherEducation: 67,
    socialDevelopment: 76,
    lifestyle: 82,
    terrorismActivity: 20,
    cyberCapabilities: 46,
    digitalDevelopment: 58,
    science: 71,
    cloning: "Banned",
    lswActivity: 81,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 36,
    name: "Mexico",
    president: "Ricardo Ortega",
    population: 128932753,
    populationRating: 70,
    motto: "The Homeland is First",
    nationality: "Mexican",
    governmentStructure: "Federal Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 34,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 49,
    militaryBudget: 60,
    intelligenceServices: 20,
    intelligenceBudget: 45,
    capitalPunishment: "Inactive",
    mediaFreedom: 53,
    lawEnforcement: 82,
    lawEnforcementBudget: 66,
    gdpNational: 70,
    gdpPerCapita: 49,
    healthcare: 75,
    higherEducation: 70,
    socialDevelopment: 77,
    lifestyle: 81,
    terrorismActivity: 24,
    cyberCapabilities: 37,
    digitalDevelopment: 52,
    science: 65,
    cloning: "Banned",
    lswActivity: 77,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 40,
    name: "Nigeria",
    president: "Emmanuel Ekpe",
    population: 206139589,
    populationRating: 75,
    motto: "Unity and Faith, Peace and Progress",
    nationality: "Nigerian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 25,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 52,
    militaryBudget: 55,
    intelligenceServices: 20,
    intelligenceBudget: 39,
    capitalPunishment: "Active",
    mediaFreedom: 60,
    lawEnforcement: 87,
    lawEnforcementBudget: 61,
    gdpNational: 58,
    gdpPerCapita: 35,
    healthcare: 35,
    higherEducation: 49,
    socialDevelopment: 53,
    lifestyle: 75,
    terrorismActivity: 82,
    cyberCapabilities: 54,
    digitalDevelopment: 31,
    science: 50,
    cloning: "Legal",
    lswActivity: 88,
    lswRegulations: "Banned",
    vigilantism: "Regulated",
    presidentGender: "Male",
  },
  {
    code: 27,
    name: "Iran",
    president: "",
    population: 83992949,
    populationRating: 58,
    motto: "God is the Greatest",
    nationality: "Iranian",
    governmentStructure: "Theocratic Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 26,
    presidentialTerm: 0,
    leaderTitle: "Supreme Leader",
    militaryServices: 69,
    militaryBudget: 69,
    intelligenceServices: 60,
    intelligenceBudget: 65,
    capitalPunishment: "Active",
    mediaFreedom: 32,
    lawEnforcement: 56,
    lawEnforcementBudget: 47,
    gdpNational: 69,
    gdpPerCapita: 38,
    healthcare: 59,
    higherEducation: 75,
    socialDevelopment: 78,
    lifestyle: 73,
    terrorismActivity: 50,
    cyberCapabilities: 20,
    digitalDevelopment: 51,
    science: 70,
    cloning: "Legal",
    lswActivity: 67,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 65,
    name: "Turkey",
    president: "",
    population: 84339067,
    populationRating: 58,
    motto: "Either independence or death",
    nationality: "Turk",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 36,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 70,
    militaryBudget: 67,
    intelligenceServices: 60,
    intelligenceBudget: 62,
    capitalPunishment: "Inactive",
    mediaFreedom: 50,
    lawEnforcement: 21,
    lawEnforcementBudget: 35,
    gdpNational: 64,
    gdpPerCapita: 48,
    healthcare: 77,
    higherEducation: 73,
    socialDevelopment: 82,
    lifestyle: 79,
    terrorismActivity: 56,
    cyberCapabilities: 54,
    digitalDevelopment: 58,
    science: 70,
    cloning: "Banned",
    lswActivity: 67,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 47,
    name: "Saudi Arabia",
    president: "",
    population: 34813871,
    populationRating: 52,
    motto: "There is no God other than God and Muhammad is the Messenger of God",
    nationality: "Saudi",
    governmentStructure: "Monarchy",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 53,
    presidentialTerm: 0,
    leaderTitle: "King",
    militaryServices: 63,
    militaryBudget: 64,
    intelligenceServices: 40,
    intelligenceBudget: 52,
    capitalPunishment: "Active",
    mediaFreedom: 28,
    lawEnforcement: 32,
    lawEnforcementBudget: 47,
    gdpNational: 64,
    gdpPerCapita: 61,
    healthcare: 75,
    higherEducation: 78,
    socialDevelopment: 85,
    lifestyle: 78,
    terrorismActivity: 31,
    cyberCapabilities: 83,
    digitalDevelopment: 63,
    science: 32,
    cloning: "Regulated",
    lswActivity: 49,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 53,
    name: "South Africa",
    president: "",
    population: 59308690,
    populationRating: 57,
    motto: "Diverse people unite or Unity in Diversity",
    nationality: "South African",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 46,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 53,
    militaryBudget: 64,
    intelligenceServices: 20,
    intelligenceBudget: 48,
    capitalPunishment: "Inactive",
    mediaFreedom: 78,
    lawEnforcement: 58,
    lawEnforcementBudget: 49,
    gdpNational: 75,
    gdpPerCapita: 39,
    healthcare: 77,
    higherEducation: 72,
    socialDevelopment: 71,
    lifestyle: 78,
    terrorismActivity: 20,
    cyberCapabilities: 36,
    digitalDevelopment: 49,
    science: 62,
    cloning: "Banned",
    lswActivity: 65,
    lswRegulations: "Banned",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 42,
    name: "Pakistan",
    president: "",
    population: 220892340,
    populationRating: 76,
    motto: "Faith, Unity, Discipline",
    nationality: "Pakistani",
    governmentStructure: "Federal Republic",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 29,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 74,
    militaryBudget: 65,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 53,
    lawEnforcement: 54,
    lawEnforcementBudget: 43,
    gdpNational: 55,
    gdpPerCapita: 32,
    healthcare: 35,
    higherEducation: 40,
    socialDevelopment: 55,
    lifestyle: 57,
    terrorismActivity: 78,
    cyberCapabilities: 42,
    digitalDevelopment: 32,
    science: 45,
    cloning: "Legal",
    lswActivity: 82,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 20,
    name: "Egypt",
    president: "",
    population: 102334404,
    populationRating: 69,
    motto: "None",
    nationality: "Egyptian",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 35,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 71,
    militaryBudget: 64,
    intelligenceServices: 60,
    intelligenceBudget: 58,
    capitalPunishment: "Active",
    mediaFreedom: 35,
    lawEnforcement: 44,
    lawEnforcementBudget: 40,
    gdpNational: 56,
    gdpPerCapita: 36,
    healthcare: 59,
    higherEducation: 61,
    socialDevelopment: 70,
    lifestyle: 77,
    terrorismActivity: 68,
    cyberCapabilities: 57,
    digitalDevelopment: 46,
    science: 59,
    cloning: "Banned",
    lswActivity: 73,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 26,
    name: "Indonesia",
    president: "",
    population: 273523615,
    populationRating: 78,
    motto: "Unity in diversity",
    nationality: "Indonesian",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 40,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 68,
    militaryBudget: 69,
    intelligenceServices: 40,
    intelligenceBudget: 55,
    capitalPunishment: "Active",
    mediaFreedom: 62,
    lawEnforcement: 31,
    lawEnforcementBudget: 40,
    gdpNational: 70,
    gdpPerCapita: 48,
    healthcare: 70,
    higherEducation: 65,
    socialDevelopment: 71,
    lifestyle: 79,
    terrorismActivity: 55,
    cyberCapabilities: 38,
    digitalDevelopment: 46,
    science: 58,
    cloning: "Banned",
    lswActivity: 84,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 67,
    name: "United Arab Emirates",
    president: "",
    population: 9890402,
    populationRating: 44,
    motto: "God, Nation, President",
    nationality: "Emirian",
    governmentStructure: "Emirate",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 72,
    presidentialTerm: 0,
    leaderTitle: "President",
    militaryServices: 51,
    militaryBudget: 54,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Active",
    mediaFreedom: 56,
    lawEnforcement: 59,
    lawEnforcementBudget: 69,
    gdpNational: 56,
    gdpPerCapita: 78,
    healthcare: 75,
    higherEducation: 80,
    socialDevelopment: 89,
    lifestyle: 84,
    terrorismActivity: 0,
    cyberCapabilities: 40,
    digitalDevelopment: 68,
    science: 40,
    cloning: "Banned",
    lswActivity: 20,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 31,
    name: "Italy",
    president: "Paolo Protti",
    population: 60461826,
    populationRating: 57,
    motto: "Union, Strength and Liberty!",
    nationality: "Italian",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 57,
    presidentialTerm: 7,
    leaderTitle: "President",
    militaryServices: 72,
    militaryBudget: 76,
    intelligenceServices: 40,
    intelligenceBudget: 60,
    capitalPunishment: "Inactive",
    mediaFreedom: 76,
    lawEnforcement: 35,
    lawEnforcementBudget: 52,
    gdpNational: 80,
    gdpPerCapita: 68,
    healthcare: 80,
    higherEducation: 79,
    socialDevelopment: 89,
    lifestyle: 87,
    terrorismActivity: 36,
    cyberCapabilities: 79,
    digitalDevelopment: 68,
    science: 75,
    cloning: "Banned",
    lswActivity: 32,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "Male",
  },
  {
    code: 77,
    name: "Poland",
    president: "",
    population: 37846611,
    populationRating: 52,
    motto: "For our freedom and yours",
    nationality: "Polish",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 54,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 54,
    militaryBudget: 59,
    intelligenceServices: 40,
    intelligenceBudget: 52,
    capitalPunishment: "Inactive",
    mediaFreedom: 71,
    lawEnforcement: 14,
    lawEnforcementBudget: 37,
    gdpNational: 63,
    gdpPerCapita: 59,
    healthcare: 85,
    higherEducation: 86,
    socialDevelopment: 88,
    lifestyle: 82,
    terrorismActivity: 0,
    cyberCapabilities: 86,
    digitalDevelopment: 66,
    science: 68,
    cloning: "Banned",
    lswActivity: 52,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 4,
    name: "Argentina",
    president: "",
    population: 45195564,
    populationRating: 54,
    motto: "In Union and Liberty",
    nationality: "Argentinean",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 41,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 49,
    militaryBudget: 53,
    intelligenceServices: 20,
    intelligenceBudget: 39,
    capitalPunishment: "Inactive",
    mediaFreedom: 71,
    lawEnforcement: 37,
    lawEnforcementBudget: 44,
    gdpNational: 57,
    gdpPerCapita: 51,
    healthcare: 70,
    higherEducation: 65,
    socialDevelopment: 83,
    lifestyle: 82,
    terrorismActivity: 26,
    cyberCapabilities: 48,
    digitalDevelopment: 60,
    science: 27,
    cloning: "Banned",
    lswActivity: 24,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 66,
    name: "Ukraine",
    president: "",
    population: 43733762,
    populationRating: 54,
    motto: "Glory to Ukraine! Glory to the heroes!",
    nationality: "Ukrainian",
    governmentStructure: "Republic",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 31,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 57,
    militaryBudget: 55,
    intelligenceServices: 40,
    intelligenceBudget: 46,
    capitalPunishment: "Inactive",
    mediaFreedom: 67,
    lawEnforcement: 23,
    lawEnforcementBudget: 30,
    gdpNational: 52,
    gdpPerCapita: 36,
    healthcare: 77,
    higherEducation: 79,
    socialDevelopment: 77,
    lifestyle: 79,
    terrorismActivity: 23,
    cyberCapabilities: 75,
    digitalDevelopment: 55,
    science: 32,
    cloning: "Banned",
    lswActivity: 55,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 18,
    name: "Colombia",
    president: "",
    population: 50882891,
    populationRating: 56,
    motto: "Freedom and order",
    nationality: "Colombian",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 37,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 48,
    militaryBudget: 52,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 56,
    lawEnforcement: 17,
    lawEnforcementBudget: 28,
    gdpNational: 55,
    gdpPerCapita: 39,
    healthcare: 65,
    higherEducation: 68,
    socialDevelopment: 76,
    lifestyle: 77,
    terrorismActivity: 70,
    cyberCapabilities: 46,
    digitalDevelopment: 52,
    science: 50,
    cloning: "Regulated",
    lswActivity: 57,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 43,
    name: "Peru",
    president: "",
    population: 32971854,
    populationRating: 52,
    motto: "Steady and happy for the union",
    nationality: "Peruvian",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 36,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 47,
    militaryBudget: 51,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Rare",
    mediaFreedom: 68,
    lawEnforcement: 34,
    lawEnforcementBudget: 38,
    gdpNational: 55,
    gdpPerCapita: 41,
    healthcare: 75,
    higherEducation: 74,
    socialDevelopment: 77,
    lifestyle: 79,
    terrorismActivity: 44,
    cyberCapabilities: 40,
    digitalDevelopment: 48,
    science: 39,
    cloning: "Regulated",
    lswActivity: 48,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 44,
    name: "Philippines",
    president: "",
    population: 10099265,
    populationRating: 45,
    motto: "For God, for the people, for nature and for the country",
    nationality: "Filipino",
    governmentStructure: "Republic",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 34,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 46,
    militaryBudget: 51,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Inactive",
    mediaFreedom: 54,
    lawEnforcement: 28,
    lawEnforcementBudget: 32,
    gdpNational: 56,
    gdpPerCapita: 36,
    healthcare: 65,
    higherEducation: 67,
    socialDevelopment: 71,
    lifestyle: 82,
    terrorismActivity: 67,
    cyberCapabilities: 63,
    digitalDevelopment: 46,
    science: 38,
    cloning: "Regulated",
    lswActivity: 75,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 64,
    name: "Thailand",
    president: "",
    population: 69799978,
    populationRating: 57,
    motto: "Nation, Religion, King",
    nationality: "Thai",
    governmentStructure: "Constitutional Monarchy",
    governmentPerception: "Flawed Democracy",
    governmentCorruption: 34,
    presidentialTerm: 4,
    leaderTitle: "Monarch",
    militaryServices: 54,
    militaryBudget: 42,
    intelligenceServices: 20,
    intelligenceBudget: 25,
    capitalPunishment: "Inactive",
    mediaFreedom: 54,
    lawEnforcement: 34,
    lawEnforcementBudget: 38,
    gdpNational: 30,
    gdpPerCapita: 42,
    healthcare: 70,
    higherEducation: 68,
    socialDevelopment: 77,
    lifestyle: 83,
    terrorismActivity: 57,
    cyberCapabilities: 64,
    digitalDevelopment: 56,
    science: 35,
    cloning: "Banned",
    lswActivity: 66,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 71,
    name: "Vietnam",
    president: "",
    population: 97338579,
    populationRating: 60,
    motto: "Independence, Liberty, Happiness",
    nationality: "Vietnamese",
    governmentStructure: "Communist state",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 36,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 54,
    militaryBudget: 55,
    intelligenceServices: 40,
    intelligenceBudget: 48,
    capitalPunishment: "Active",
    mediaFreedom: 31,
    lawEnforcement: 38,
    lawEnforcementBudget: 37,
    gdpNational: 55,
    gdpPerCapita: 35,
    healthcare: 65,
    higherEducation: 63,
    socialDevelopment: 70,
    lifestyle: 78,
    terrorismActivity: 20,
    cyberCapabilities: 36,
    digitalDevelopment: 47,
    science: 44,
    cloning: "Regulated",
    lswActivity: 29,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 98,
    name: "Chile",
    president: "",
    population: 19116201,
    populationRating: 49,
    motto: "Through Reason Or By Force",
    nationality: "Chilean",
    governmentStructure: "Republic",
    governmentPerception: "Full Democracy",
    governmentCorruption: 68,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 45,
    militaryBudget: 50,
    intelligenceServices: 20,
    intelligenceBudget: 38,
    capitalPunishment: "Rare",
    mediaFreedom: 72,
    lawEnforcement: 65,
    lawEnforcementBudget: 61,
    gdpNational: 55,
    gdpPerCapita: 56,
    healthcare: 90,
    higherEducation: 81,
    socialDevelopment: 85,
    lifestyle: 77,
    terrorismActivity: 64,
    cyberCapabilities: 59,
    digitalDevelopment: 61,
    science: 57,
    cloning: "Regulated",
    lswActivity: 35,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 70,
    name: "Venezuela",
    president: "",
    population: 28435940,
    populationRating: 51,
    motto: "God and Federation",
    nationality: "Venezuelan",
    governmentStructure: "Federal Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 48,
    militaryBudget: 49,
    intelligenceServices: 20,
    intelligenceBudget: 35,
    capitalPunishment: "Inactive",
    mediaFreedom: 45,
    lawEnforcement: 22,
    lawEnforcementBudget: 29,
    gdpNational: 50,
    gdpPerCapita: 35,
    healthcare: 40,
    higherEducation: 70,
    socialDevelopment: 71,
    lifestyle: 74,
    terrorismActivity: 0,
    cyberCapabilities: 32,
    digitalDevelopment: 43,
    science: 37,
    cloning: "Legal",
    lswActivity: 44,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 41,
    name: "North Korea",
    president: "",
    population: 25778816,
    populationRating: 51,
    motto: "Strong and Prosperous Nation",
    nationality: "North Korean",
    governmentStructure: "Communist state",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 5,
    leaderTitle: "President of State Affairs",
    militaryServices: 53,
    militaryBudget: 48,
    intelligenceServices: 80,
    intelligenceBudget: 62,
    capitalPunishment: "Active",
    mediaFreedom: 20,
    lawEnforcement: 31,
    lawEnforcementBudget: 27,
    gdpNational: 43,
    gdpPerCapita: 22,
    healthcare: 40,
    higherEducation: 35,
    socialDevelopment: 20,
    lifestyle: 25,
    terrorismActivity: 0,
    cyberCapabilities: 83,
    digitalDevelopment: 25,
    science: 20,
    cloning: "Legal",
    lswActivity: 41,
    lswRegulations: "Legal",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 52,
    name: "Somalia",
    president: "",
    population: 15893222,
    populationRating: 48,
    motto: "Arise Somalis!",
    nationality: "Somali",
    governmentStructure: "Federal Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 20,
    militaryBudget: 25,
    intelligenceServices: 20,
    intelligenceBudget: 25,
    capitalPunishment: "Active",
    mediaFreedom: 54,
    lawEnforcement: 51,
    lawEnforcementBudget: 36,
    gdpNational: 29,
    gdpPerCapita: 21,
    healthcare: 20,
    higherEducation: 28,
    socialDevelopment: 36,
    lifestyle: 38,
    terrorismActivity: 83,
    cyberCapabilities: 0,
    digitalDevelopment: 20,
    science: 28,
    cloning: "Legal",
    lswActivity: 22,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 96,
    name: "Afghanistan",
    president: "",
    population: 38928345,
    populationRating: 53,
    motto: "He is the messenger of God",
    nationality: "Afghan",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 27,
    militaryBudget: 35,
    intelligenceServices: 20,
    intelligenceBudget: 32,
    capitalPunishment: "Active",
    mediaFreedom: 59,
    lawEnforcement: 60,
    lawEnforcementBudget: 41,
    gdpNational: 43,
    gdpPerCapita: 21,
    healthcare: 20,
    higherEducation: 41,
    socialDevelopment: 49,
    lifestyle: 69,
    terrorismActivity: 90,
    cyberCapabilities: 20,
    digitalDevelopment: 20,
    science: 20,
    cloning: "Legal",
    lswActivity: 53,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 28,
    name: "Iraq",
    president: "",
    population: 40222493,
    populationRating: 54,
    motto: "God is the Greatest",
    nationality: "Iraqi",
    governmentStructure: "Parliamentary democracy",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 25,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 52,
    militaryBudget: 52,
    intelligenceServices: 20,
    intelligenceBudget: 36,
    capitalPunishment: "Active",
    mediaFreedom: 35,
    lawEnforcement: 47,
    lawEnforcementBudget: 43,
    gdpNational: 52,
    gdpPerCapita: 38,
    healthcare: 35,
    higherEducation: 55,
    socialDevelopment: 67,
    lifestyle: 75,
    terrorismActivity: 85,
    cyberCapabilities: 20,
    digitalDevelopment: 43,
    science: 40,
    cloning: "Legal",
    lswActivity: 55,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 60,
    name: "Syria",
    president: "",
    population: 17500658,
    populationRating: 48,
    motto: "Unity, Freedom, Socialism",
    nationality: "Syrian",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 7,
    leaderTitle: "President",
    militaryServices: 48,
    militaryBudget: 46,
    intelligenceServices: 40,
    intelligenceBudget: 42,
    capitalPunishment: "Active",
    mediaFreedom: 32,
    lawEnforcement: 76,
    lawEnforcementBudget: 54,
    gdpNational: 43,
    gdpPerCapita: 31,
    healthcare: 20,
    higherEducation: 40,
    socialDevelopment: 56,
    lifestyle: 32,
    terrorismActivity: 82,
    cyberCapabilities: 20,
    digitalDevelopment: 33,
    science: 20,
    cloning: "Legal",
    lswActivity: 32,
    lswRegulations: "Banned",
    vigilantism: "Legal",
    presidentGender: "",
  },
  {
    code: 72,
    name: "Yemen",
    president: "",
    population: 29825964,
    populationRating: 51,
    motto: "God, Homeland, Revolution, Unity",
    nationality: "Yemeni",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 20,
    presidentialTerm: 7,
    leaderTitle: "Chairman",
    militaryServices: 37,
    militaryBudget: 41,
    intelligenceServices: 20,
    intelligenceBudget: 32,
    capitalPunishment: "Active",
    mediaFreedom: 46,
    lawEnforcement: 85,
    lawEnforcementBudget: 58,
    gdpNational: 44,
    gdpPerCapita: 30,
    healthcare: 20,
    higherEducation: 35,
    socialDevelopment: 47,
    lifestyle: 69,
    terrorismActivity: 58,
    cyberCapabilities: 0,
    digitalDevelopment: 20,
    science: 24,
    cloning: "Legal",
    lswActivity: 45,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 11,
    name: "Belarus",
    president: "",
    population: 9449323,
    populationRating: 44,
    motto: "Long Live Belarus!",
    nationality: "Belarusian",
    governmentStructure: "Dictatorship",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 42,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 46,
    militaryBudget: 46,
    intelligenceServices: 20,
    intelligenceBudget: 33,
    capitalPunishment: "Active",
    mediaFreedom: 38,
    lawEnforcement: 44,
    lawEnforcementBudget: 42,
    gdpNational: 46,
    gdpPerCapita: 39,
    healthcare: 75,
    higherEducation: 83,
    socialDevelopment: 82,
    lifestyle: 76,
    terrorismActivity: 0,
    cyberCapabilities: 53,
    digitalDevelopment: 62,
    science: 38,
    cloning: "Legal",
    lswActivity: 45,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 21,
    name: "Ethiopia",
    president: "",
    population: 114963588,
    populationRating: 69,
    motto: "Ethiopia holds up her hands unto God",
    nationality: "Ethiopian",
    governmentStructure: "Federal Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 41,
    presidentialTerm: 6,
    leaderTitle: "President",
    militaryServices: 43,
    militaryBudget: 46,
    intelligenceServices: 20,
    intelligenceBudget: 35,
    capitalPunishment: "Active",
    mediaFreedom: 66,
    lawEnforcement: 67,
    lawEnforcementBudget: 47,
    gdpNational: 49,
    gdpPerCapita: 26,
    healthcare: 35,
    higherEducation: 34,
    socialDevelopment: 48,
    lifestyle: 73,
    terrorismActivity: 37,
    cyberCapabilities: 32,
    digitalDevelopment: 20,
    science: 42,
    cloning: "Legal",
    lswActivity: 75,
    lswRegulations: "Regulated",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 19,
    name: "DR Congo",
    president: "",
    population: 89561403,
    populationRating: 58,
    motto: "Justice, Peace, Work",
    nationality: "Congolese",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 24,
    presidentialTerm: 4,
    leaderTitle: "President",
    militaryServices: 27,
    militaryBudget: 34,
    intelligenceServices: 20,
    intelligenceBudget: 30,
    capitalPunishment: "Inactive",
    mediaFreedom: 51,
    lawEnforcement: 51,
    lawEnforcementBudget: 43,
    gdpNational: 40,
    gdpPerCapita: 34,
    healthcare: 30,
    higherEducation: 54,
    socialDevelopment: 48,
    lifestyle: 70,
    terrorismActivity: 0,
    cyberCapabilities: 0,
    digitalDevelopment: 20,
    science: 21,
    cloning: "Legal",
    lswActivity: 39,
    lswRegulations: "Banned",
    vigilantism: "Banned",
    presidentGender: "",
  },
  {
    code: 85,
    name: "Kenya",
    president: "",
    population: 53771296,
    populationRating: 56,
    motto: "All pull together",
    nationality: "Kenyan",
    governmentStructure: "Republic",
    governmentPerception: "Hybrid Regime",
    governmentCorruption: 33,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 36,
    militaryBudget: 43,
    intelligenceServices: 20,
    intelligenceBudget: 35,
    capitalPunishment: "Rare",
    mediaFreedom: 66,
    lawEnforcement: 25,
    lawEnforcementBudget: 30,
    gdpNational: 50,
    gdpPerCapita: 34,
    healthcare: 50,
    higherEducation: 53,
    socialDevelopment: 57,
    lifestyle: 75,
    terrorismActivity: 61,
    cyberCapabilities: 49,
    digitalDevelopment: 37,
    science: 38,
    cloning: "Regulated",
    lswActivity: 60,
    lswRegulations: "Regulated",
    vigilantism: "Regulated",
    presidentGender: "",
  },
  {
    code: 57,
    name: "Sudan",
    president: "",
    population: 43849260,
    populationRating: 54,
    motto: "Victory is Ours",
    nationality: "Sudanese",
    governmentStructure: "Federal Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 21,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 40,
    militaryBudget: 44,
    intelligenceServices: 20,
    intelligenceBudget: 34,
    capitalPunishment: "Active",
    mediaFreedom: 47,
    lawEnforcement: 28,
    lawEnforcementBudget: 31,
    gdpNational: 47,
    gdpPerCapita: 33,
    healthcare: 35,
    higherEducation: 34,
    socialDevelopment: 51,
    lifestyle: 32,
    terrorismActivity: 20,
    cyberCapabilities: 20,
    digitalDevelopment: 22,
    science: 20,
    cloning: "Legal",
    lswActivity: 55,
    lswRegulations: "Regulated",
    vigilantism: "Legal",
    presidentGender: "",
  },
  {
    code: 3,
    name: "Angola",
    president: "Rafael Mendonça",
    population: 32864556,
    populationRating: 52,
    motto: "Each endeavouring, all achieving",
    nationality: "Angolan",
    governmentStructure: "Republic",
    governmentPerception: "Authoritarian Regime",
    governmentCorruption: 32,
    presidentialTerm: 5,
    leaderTitle: "President",
    militaryServices: 42,
    militaryBudget: 45,
    intelligenceServices: 20,
    intelligenceBudget: 34,
    capitalPunishment: "Inactive",
    mediaFreedom: 65,
    lawEnforcement: 67,
    lawEnforcementBudget: 51,
    gdpNational: 47,
    gdpPerCapita: 35,
    healthcare: 30,
    higherEducation: 47,
    socialDevelopment: 57,
    lifestyle: 73,
    terrorismActivity: 20,
    cyberCapabilities: 20,
    digitalDevelopment: 22,
    science: 25,
    cloning: "Legal",
    lswActivity: 48,
    lswRegulations: "Banned",
    vigilantism: "Regulated",
    presidentGender: "Male",
  },
]

// Get cities for a specific country
export function getCitiesForCountry(countryName: string): City[] {
  return CITIES.filter((city) => city.country.toLowerCase() === countryName.toLowerCase())
}

// City data - a subset for demonstration (full data would be imported from CSV)
export const CITIES: City[] = [
  {
    sector: "LJ5",
    countryCode: 96,
    cultureCode: 14,
    name: "Kabul",
    country: "Afghanistan",
    population: 4221532,
    populationRating: 6,
    populationType: "City",
    cityTypes: ["Military", "Political"],
    hvt: "",
    crimeIndex: 76.06,
    safetyIndex: 23.94,
  },
  {
    sector: "LD4",
    countryCode: 96,
    cultureCode: 14,
    name: "Herat",
    country: "Afghanistan",
    population: 605575,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Political", "Educational", "Company"],
    hvt: "",
    crimeIndex: 57.0,
    safetyIndex: 43.0,
  },
  {
    sector: "",
    countryCode: 2,
    cultureCode: 1,
    name: "Algiers",
    country: "Algeria",
    population: 2767661,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political", "Company"],
    hvt: "",
    crimeIndex: 52.05,
    safetyIndex: 47.95,
  },
  {
    sector: "IV3",
    countryCode: 3,
    cultureCode: 3,
    name: "Luanda",
    country: "Angola",
    population: 8329798,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial"],
    hvt: "",
    crimeIndex: 67.52,
    safetyIndex: 32.48,
  },
  {
    sector: "",
    countryCode: 4,
    cultureCode: 12,
    name: "Buenos Aires",
    country: "Argentina",
    population: 15153729,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Company", "Industrial", "Educational", "Political"],
    hvt: "",
    crimeIndex: 62.58,
    safetyIndex: 37.42,
  },
  {
    sector: "OY5",
    countryCode: 6,
    cultureCode: 11,
    name: "Melbourne",
    country: "Australia",
    population: 4967733,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Educational", "Resort", "Industrial", "Company"],
    hvt: "",
    crimeIndex: 44.49,
    safetyIndex: 55.51,
  },
  {
    sector: "PE5",
    countryCode: 6,
    cultureCode: 11,
    name: "Sydney",
    country: "Australia",
    population: 4925987,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Political", "Industrial", "Seaport"],
    hvt: "",
    crimeIndex: 33.67,
    safetyIndex: 66.33,
  },
  {
    sector: "",
    countryCode: 7,
    cultureCode: 9,
    name: "Vienna",
    country: "Austria",
    population: 1929944,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Industrial", "Educational", "Political"],
    hvt: "",
    crimeIndex: 25.26,
    safetyIndex: 74.74,
  },
  {
    sector: "",
    countryCode: 10,
    cultureCode: 5,
    name: "Dhaka",
    country: "Bangladesh",
    population: 21005860,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Company", "Industrial", "Military"],
    hvt: "",
    crimeIndex: 64.94,
    safetyIndex: 35.06,
  },
  {
    sector: "",
    countryCode: 11,
    cultureCode: 10,
    name: "Minsk",
    country: "Belarus",
    population: 2028104,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political", "Industrial", "Company", "Educational"],
    hvt: "",
    crimeIndex: 61.75,
    safetyIndex: 38.25,
  },
  {
    sector: "",
    countryCode: 12,
    cultureCode: 9,
    name: "Brussels",
    country: "Belgium",
    population: 2080788,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Educational", "Company"],
    hvt: "",
    crimeIndex: 50.8,
    safetyIndex: 49.2,
  },
  {
    sector: "GA4",
    countryCode: 15,
    cultureCode: 12,
    name: "Sao Paulo",
    country: "Brazil",
    population: 22043028,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Industrial", "Political", "Company", "Educational"],
    hvt: "",
    crimeIndex: 70.38,
    safetyIndex: 29.62,
  },
  {
    sector: "GG5",
    countryCode: 15,
    cultureCode: 12,
    name: "Rio de Janeiro",
    country: "Brazil",
    population: 13458075,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Company", "Military", "Resort", "Temple"],
    hvt: "",
    crimeIndex: 77.52,
    safetyIndex: 22.48,
  },
  {
    sector: "EO4",
    countryCode: 16,
    cultureCode: 14,
    name: "Toronto",
    country: "Canada",
    population: 6196731,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Company", "Educational", "Political"],
    hvt: "",
    crimeIndex: 39.84,
    safetyIndex: 60.16,
  },
  {
    sector: "EU4",
    countryCode: 16,
    cultureCode: 14,
    name: "Montreal",
    country: "Canada",
    population: 4220566,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Industrial", "Temple", "Military"],
    hvt: "",
    crimeIndex: 29.15,
    safetyIndex: 70.85,
  },
  {
    sector: "CR4",
    countryCode: 16,
    cultureCode: 14,
    name: "Vancouver",
    country: "Canada",
    population: 2581079,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Company", "Temple", "Mining"],
    hvt: "",
    crimeIndex: 36.45,
    safetyIndex: 63.55,
  },
  {
    sector: "",
    countryCode: 33,
    cultureCode: 6,
    name: "Beijing",
    country: "China",
    population: 21540000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Industrial", "Educational", "Company"],
    hvt: "",
    crimeIndex: 32.1,
    safetyIndex: 67.9,
  },
  {
    sector: "",
    countryCode: 33,
    cultureCode: 6,
    name: "Shanghai",
    country: "China",
    population: 27796000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Company", "Industrial", "Seaport", "Educational"],
    hvt: "",
    crimeIndex: 29.51,
    safetyIndex: 70.49,
  },
  {
    sector: "EV3",
    countryCode: 18,
    cultureCode: 12,
    name: "Bogota",
    country: "Colombia",
    population: 10978360,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Industrial", "Company", "Educational"],
    hvt: "",
    crimeIndex: 62.81,
    safetyIndex: 37.19,
  },
  {
    sector: "",
    countryCode: 107,
    cultureCode: 9,
    name: "Copenhagen",
    country: "Denmark",
    population: 1346485,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Industrial", "Company", "Educational"],
    hvt: "",
    crimeIndex: 27.54,
    safetyIndex: 72.46,
  },
  {
    sector: "JM8",
    countryCode: 20,
    cultureCode: 1,
    name: "Cairo",
    country: "Egypt",
    population: 20900604,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Industrial", "Company", "Temple", "Seaport"],
    hvt: "",
    crimeIndex: 49.97,
    safetyIndex: 50.03,
  },
  {
    sector: "",
    countryCode: 113,
    cultureCode: 9,
    name: "Helsinki",
    country: "Finland",
    population: 1304851,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Seaport", "Industrial"],
    hvt: "",
    crimeIndex: 25.27,
    safetyIndex: 74.73,
  },
  {
    sector: "IH9",
    countryCode: 22,
    cultureCode: 9,
    name: "Paris",
    country: "France",
    population: 11017230,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Educational", "Company", "Political", "Resort"],
    hvt: "",
    crimeIndex: 53.19,
    safetyIndex: 46.81,
  },
  {
    sector: "",
    countryCode: 23,
    cultureCode: 9,
    name: "Berlin",
    country: "Germany",
    population: 3562038,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Educational", "Political", "Company", "Temple"],
    hvt: "",
    crimeIndex: 41.14,
    safetyIndex: 58.86,
  },
  {
    sector: "IN8",
    countryCode: 23,
    cultureCode: 9,
    name: "Hamburg",
    country: "Germany",
    population: 1789954,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Industrial", "Resort"],
    hvt: "",
    crimeIndex: 43.26,
    safetyIndex: 56.74,
  },
  {
    sector: "",
    countryCode: 23,
    cultureCode: 9,
    name: "Munich",
    country: "Germany",
    population: 1538302,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Mining", "Military"],
    hvt: "",
    crimeIndex: 17.65,
    safetyIndex: 82.35,
  },
  {
    sector: "",
    countryCode: 93,
    cultureCode: 10,
    name: "Athens",
    country: "Greece",
    population: 3153355,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Company", "Educational"],
    hvt: "",
    crimeIndex: 52.3,
    safetyIndex: 47.7,
  },
  {
    sector: "LP8",
    countryCode: 25,
    cultureCode: 5,
    name: "Delhi",
    country: "India",
    population: 30290936,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Industrial", "Company", "Educational", "Political"],
    hvt: "",
    crimeIndex: 59.18,
    safetyIndex: 40.82,
  },
  {
    sector: "LQ0",
    countryCode: 25,
    cultureCode: 5,
    name: "Mumbai",
    country: "India",
    population: 20411274,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Educational", "Company", "Temple"],
    hvt: "",
    crimeIndex: 43.15,
    safetyIndex: 56.85,
  },
  {
    sector: "",
    countryCode: 25,
    cultureCode: 5,
    name: "Kolkata",
    country: "India",
    population: 14850066,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Resort", "Industrial", "Mining"],
    hvt: "",
    crimeIndex: 47.82,
    safetyIndex: 52.18,
  },
  {
    sector: "",
    countryCode: 25,
    cultureCode: 5,
    name: "Bangalore",
    country: "India",
    population: 12326532,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Temple", "Company", "Resort", "Educational"],
    hvt: "",
    crimeIndex: 54.11,
    safetyIndex: 45.89,
  },
  {
    sector: "",
    countryCode: 26,
    cultureCode: 6,
    name: "Jakarta",
    country: "Indonesia",
    population: 10750000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Company", "Industrial", "Educational"],
    hvt: "",
    crimeIndex: 49.21,
    safetyIndex: 50.79,
  },
  {
    sector: "",
    countryCode: 27,
    cultureCode: 14,
    name: "Tehran",
    country: "Iran",
    population: 9100000,
    populationRating: 7,
    populationType: "Large City",
    cityTypes: ["Political", "Industrial", "Company", "Military"],
    hvt: "",
    crimeIndex: 40.02,
    safetyIndex: 59.98,
  },
  {
    sector: "",
    countryCode: 28,
    cultureCode: 14,
    name: "Baghdad",
    country: "Iraq",
    population: 7144000,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political", "Military", "Industrial"],
    hvt: "",
    crimeIndex: 57.35,
    safetyIndex: 42.65,
  },
  {
    sector: "",
    countryCode: 29,
    cultureCode: 9,
    name: "Dublin",
    country: "Ireland",
    population: 1388000,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Company", "Educational", "Resort"],
    hvt: "",
    crimeIndex: 49.54,
    safetyIndex: 50.46,
  },
  {
    sector: "",
    countryCode: 30,
    cultureCode: 14,
    name: "Tel Aviv",
    country: "Israel",
    population: 4500000,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Industrial", "Resort", "Military"],
    hvt: "",
    crimeIndex: 36.71,
    safetyIndex: 63.29,
  },
  {
    sector: "",
    countryCode: 31,
    cultureCode: 9,
    name: "Rome",
    country: "Italy",
    population: 4257000,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political", "Temple", "Educational", "Resort"],
    hvt: "",
    crimeIndex: 42.68,
    safetyIndex: 57.32,
  },
  {
    sector: "",
    countryCode: 31,
    cultureCode: 9,
    name: "Milan",
    country: "Italy",
    population: 3200000,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Company", "Industrial", "Educational"],
    hvt: "",
    crimeIndex: 48.13,
    safetyIndex: 51.87,
  },
  {
    sector: "",
    countryCode: 35,
    cultureCode: 6,
    name: "Tokyo",
    country: "Japan",
    population: 37400000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Company", "Political", "Industrial", "Educational"],
    hvt: "",
    crimeIndex: 22.15,
    safetyIndex: 77.85,
  },
  {
    sector: "",
    countryCode: 35,
    cultureCode: 6,
    name: "Osaka",
    country: "Japan",
    population: 19280000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Industrial", "Company", "Seaport", "Resort"],
    hvt: "",
    crimeIndex: 19.92,
    safetyIndex: 80.08,
  },
  {
    sector: "",
    countryCode: 85,
    cultureCode: 2,
    name: "Nairobi",
    country: "Kenya",
    population: 4734881,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political", "Company", "Industrial"],
    hvt: "",
    crimeIndex: 67.39,
    safetyIndex: 32.61,
  },
  {
    sector: "",
    countryCode: 36,
    cultureCode: 8,
    name: "Mexico City",
    country: "Mexico",
    population: 21782000,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Industrial", "Company", "Educational"],
    hvt: "",
    crimeIndex: 66.76,
    safetyIndex: 33.24,
  },
  {
    sector: "",
    countryCode: 89,
    cultureCode: 9,
    name: "Amsterdam",
    country: "Netherlands",
    population: 1148972,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Educational", "Company"],
    hvt: "",
    crimeIndex: 33.68,
    safetyIndex: 66.32,
  },
  {
    sector: "",
    countryCode: 40,
    cultureCode: 2,
    name: "Lagos",
    country: "Nigeria",
    population: 14368332,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Resort"],
    hvt: "",
    crimeIndex: 64.82,
    safetyIndex: 35.18,
  },
  {
    sector: "",
    countryCode: 40,
    cultureCode: 2,
    name: "Abuja",
    country: "Nigeria",
    population: 3277740,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Political"],
    hvt: "",
    crimeIndex: 58.98,
    safetyIndex: 40.43,
  },
  {
    sector: "IN6",
    countryCode: 162,
    cultureCode: 9,
    name: "Oslo",
    country: "Norway",
    population: 1041377,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Company", "Educational", "Political", "Seaport"],
    hvt: "",
    crimeIndex: 35.01,
    safetyIndex: 64.99,
  },
  {
    sector: "LD6",
    countryCode: 42,
    cultureCode: 14,
    name: "Karachi",
    country: "Pakistan",
    population: 16093786,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 54.46,
    safetyIndex: 45.54,
  },
  {
    sector: "LP7",
    countryCode: 42,
    cultureCode: 14,
    name: "Lahore",
    country: "Pakistan",
    population: 12642423,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 39.56,
    safetyIndex: 60.44,
  },
  {
    sector: "",
    countryCode: 77,
    cultureCode: 10,
    name: "Warsaw",
    country: "Poland",
    population: 1783251,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 26.44,
    safetyIndex: 73.56,
  },
  {
    sector: "",
    countryCode: 78,
    cultureCode: 9,
    name: "Lisbon",
    country: "Portugal",
    population: 2956879,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 28.24,
    safetyIndex: 71.76,
  },
  {
    sector: "JY3",
    countryCode: 45,
    cultureCode: 10,
    name: "Moscow",
    country: "Russia",
    population: 12537954,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: ["Political", "Temple", "Educational", "Industrial"],
    hvt: "",
    crimeIndex: 38.77,
    safetyIndex: 61.23,
  },
  {
    sector: "JM0",
    countryCode: 45,
    cultureCode: 10,
    name: "Saint Petersburg",
    country: "Russia",
    population: 5467808,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Seaport", "Educational"],
    hvt: "",
    crimeIndex: 39.43,
    safetyIndex: 60.57,
  },
  {
    sector: "KF2",
    countryCode: 47,
    cultureCode: 14,
    name: "Riyadh",
    country: "Saudi Arabia",
    population: 7231447,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Political", "Military"],
    hvt: "",
    crimeIndex: 27.11,
    safetyIndex: 72.89,
  },
  {
    sector: "",
    countryCode: 51,
    cultureCode: 6,
    name: "Singapore",
    country: "Singapore",
    population: 5935053,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 32.98,
    safetyIndex: 67.02,
  },
  {
    sector: "",
    countryCode: 53,
    cultureCode: 3,
    name: "Johannesburg",
    country: "South Africa",
    population: 5782747,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 80.65,
    safetyIndex: 19.35,
  },
  {
    sector: "JB9",
    countryCode: 53,
    cultureCode: 3,
    name: "Cape Town",
    country: "South Africa",
    population: 4617560,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 73.78,
    safetyIndex: 26.22,
  },
  {
    sector: "",
    countryCode: 54,
    cultureCode: 6,
    name: "Seoul",
    country: "South Korea",
    population: 9963452,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 26.32,
    safetyIndex: 73.68,
  },
  {
    sector: "",
    countryCode: 55,
    cultureCode: 9,
    name: "Madrid",
    country: "Spain",
    population: 6617513,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 29.42,
    safetyIndex: 70.58,
  },
  {
    sector: "",
    countryCode: 55,
    cultureCode: 9,
    name: "Barcelona",
    country: "Spain",
    population: 5585556,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 45.51,
    safetyIndex: 54.49,
  },
  {
    sector: "IZ8",
    countryCode: 58,
    cultureCode: 9,
    name: "Stockholm",
    country: "Sweden",
    population: 1632798,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 45.1,
    safetyIndex: 54.9,
  },
  {
    sector: "",
    countryCode: 59,
    cultureCode: 9,
    name: "Zurich",
    country: "Switzerland",
    population: 1395356,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Industrial"],
    hvt: "",
    crimeIndex: 16.4,
    safetyIndex: 83.6,
  },
  {
    sector: "",
    countryCode: 64,
    cultureCode: 6,
    name: "Bangkok",
    country: "Thailand",
    population: 10539415,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 41.08,
    safetyIndex: 58.92,
  },
  {
    sector: "",
    countryCode: 65,
    cultureCode: 14,
    name: "Istanbul",
    country: "Turkey",
    population: 15190336,
    populationRating: 7,
    populationType: "Mega City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 47.5,
    safetyIndex: 52.5,
  },
  {
    sector: "",
    countryCode: 65,
    cultureCode: 14,
    name: "Ankara",
    country: "Turkey",
    population: 5117603,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 39.69,
    safetyIndex: 60.31,
  },
  {
    sector: "",
    countryCode: 67,
    cultureCode: 9,
    name: "Dubai",
    country: "United Arab Emirates",
    population: 2878344,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 16.56,
    safetyIndex: 83.44,
  },
  {
    sector: "",
    countryCode: 67,
    cultureCode: 9,
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    population: 1482816,
    populationRating: 5,
    populationType: "City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 11.54,
    safetyIndex: 88.46,
  },
  {
    sector: "IB7",
    countryCode: 68,
    cultureCode: 9,
    name: "London",
    country: "United Kingdom",
    population: 9304016,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 47.53,
    safetyIndex: 52.47,
  },
  {
    sector: "IB6",
    countryCode: 68,
    cultureCode: 9,
    name: "Manchester",
    country: "United Kingdom",
    population: 2730076,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 56.15,
    safetyIndex: 43.85,
  },
  {
    sector: "IB6",
    countryCode: 68,
    cultureCode: 9,
    name: "Birmingham",
    country: "United Kingdom",
    population: 2607437,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 59.56,
    safetyIndex: 40.44,
  },
  {
    sector: "EU6",
    countryCode: 69,
    cultureCode: 14,
    name: "New York City",
    country: "United States",
    population: 8323340,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Resort"],
    hvt: "",
    crimeIndex: 50.16,
    safetyIndex: 53.04,
  },
  {
    sector: "CR8",
    countryCode: 69,
    cultureCode: 14,
    name: "Los Angeles",
    country: "United States",
    population: 4015940,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: ["Industrial", "Military"],
    hvt: "",
    crimeIndex: 48.41,
    safetyIndex: 51.59,
  },
  {
    sector: "EC2",
    countryCode: 69,
    cultureCode: 14,
    name: "Chicago",
    country: "United States",
    population: 2694240,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 64.81,
    safetyIndex: 35.19,
  },
  {
    sector: "DW4",
    countryCode: 69,
    cultureCode: 14,
    name: "Houston",
    country: "United States",
    population: 2355000,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 57.52,
    safetyIndex: 42.48,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "Phoenix",
    country: "United States",
    population: 1680992,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 48.21,
    safetyIndex: 51.79,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "Philadelphia",
    country: "United States",
    population: 1584064,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 57.92,
    safetyIndex: 42.08,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "San Antonio",
    country: "United States",
    population: 1547253,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 46.27,
    safetyIndex: 53.73,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "San Diego",
    country: "United States",
    population: 1423851,
    populationRating: 5,
    populationType: "City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 32.45,
    safetyIndex: 67.55,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "Dallas",
    country: "United States",
    population: 1343573,
    populationRating: 5,
    populationType: "City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 58.75,
    safetyIndex: 41.25,
  },
  {
    sector: "",
    countryCode: 69,
    cultureCode: 14,
    name: "Miami",
    country: "United States",
    population: 467963,
    populationRating: 5,
    populationType: "City",
    cityTypes: ["Resort", "Seaport"],
    hvt: "",
    crimeIndex: 67.39,
    safetyIndex: 32.61,
  },
  {
    sector: "",
    countryCode: 66,
    cultureCode: 10,
    name: "Kiev",
    country: "Ukraine",
    population: 2988176,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 48.39,
    safetyIndex: 51.61,
  },
  {
    sector: "",
    countryCode: 71,
    cultureCode: 6,
    name: "Ho Chi Minh City",
    country: "Vietnam",
    population: 8993082,
    populationRating: 7,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 43.2,
    safetyIndex: 56.8,
  },
  {
    sector: "",
    countryCode: 71,
    cultureCode: 6,
    name: "Hanoi",
    country: "Vietnam",
    population: 8053663,
    populationRating: 6,
    populationType: "Large City",
    cityTypes: [],
    hvt: "",
    crimeIndex: 41.73,
    safetyIndex: 58.27,
  },
]

// Sample character data
export interface Character {
  id: string
  name: string
  codename: string
  avatar: string
  status: "idle" | "traveling" | "in-vehicle" | "hospitalized" | "in-combat"
  sectorId: string // e.g., "E14", "D21" - uses the grid coordinates
  vehicleId?: string // ID of vehicle if in-vehicle status
  vehicleType?: "aircraft" | "ground" | "sea" | "submarine" | "space"
}

export const SAMPLE_CHARACTERS: Character[] = [
  {
    id: "1",
    name: "Randall Jenkins",
    codename: "Stampede",
    avatar: "/superhero-male-with-beard.jpg",
    status: "idle",
    sectorId: "K26",
  },
  {
    id: "2",
    name: "Jake Gallagar",
    codename: "CrossFire",
    avatar: "/superhero-male-tactical-gear.jpg",
    status: "traveling",
    sectorId: "F9",
  },
  {
    id: "3",
    name: "Cissy Oliva",
    codename: "",
    avatar: "/female-agent-professional.jpg",
    status: "idle",
    sectorId: "E14",
  },
  {
    id: "4",
    name: "Alexander Stone",
    codename: "",
    avatar: "/older-man-with-beard-superhero.jpg",
    status: "hospitalized",
    sectorId: "F14",
  },
  {
    id: "5",
    name: "Task",
    codename: "",
    avatar: "/superhero-mask-tactical.jpg",
    status: "in-combat",
    sectorId: "E38",
  },
]

// Sample messages/notifications
export interface GameMessage {
  id: string
  type: "alert" | "event" | "mission" | "call"
  sender: string
  senderAvatar?: string
  content: string
  timestamp: string
  day: number
  read: boolean
}

export const SAMPLE_MESSAGES: GameMessage[] = [
  {
    id: "1",
    type: "alert",
    sender: "D. Beasly",
    content: "My identity has been discovered by the enemy - Day 27 8:22PM",
    timestamp: "8:22PM",
    day: 27,
    read: false,
  },
  {
    id: "2",
    type: "event",
    sender: "System",
    content: "Danny Beasly has went off the grid unexpectedly. (Day 27 11:52PM)",
    timestamp: "11:52PM",
    day: 27,
    read: false,
  },
  {
    id: "3",
    type: "mission",
    sender: "Alex Winter",
    content: "Alex Winter and Task Summer have started an investigation in Boston. (Day 27 11:04PM)",
    timestamp: "11:04PM",
    day: 27,
    read: false,
  },
  {
    id: "4",
    type: "event",
    sender: "System",
    content: "The Vice-President of Venezuela has been assassinated. (Day 27 - 10:38PM)",
    timestamp: "10:38PM",
    day: 27,
    read: true,
  },
  {
    id: "5",
    type: "mission",
    sender: "Cissy Oliva",
    content: "Cissy Oliva has finished an Engineering Project. (Day 27 11:21PM)",
    timestamp: "11:21PM",
    day: 27,
    read: true,
  },
]

// Investigation/Case data
export interface Investigation {
  id: string
  title: string
  type: string
  progress: number
  status: "active" | "complete" | "failed"
}

export const SAMPLE_INVESTIGATIONS: Investigation[] = [
  {
    id: "1",
    title: "Senator Kidnapped",
    type: "Suspect",
    progress: 75,
    status: "active",
  },
]

// Helper functions
export function formatPopulation(pop: number): string {
  if (pop >= 1000000000) {
    return `${(pop / 1000000000).toFixed(2)}B`
  }
  if (pop >= 1000000) {
    return `${(pop / 1000000).toFixed(1)}M`
  }
  if (pop >= 1000) {
    return `${(pop / 1000).toFixed(0)}K`
  }
  return pop.toString()
}

export function getRatingLabel(value: number): string {
  if (value >= 80) return "EXTREMELY HIGH"
  if (value >= 60) return "VERY HIGH"
  if (value >= 40) return "HIGH"
  if (value >= 20) return "MEDIUM"
  if (value > 0) return "LOW"
  return "VERY LOW"
}

export function getRatingColor(value: number): string {
  if (value >= 80) return "text-green-600"
  if (value >= 60) return "text-green-500"
  if (value >= 40) return "text-yellow-500"
  if (value >= 20) return "text-orange-500"
  return "text-red-500"
}
